// netlify/functions/send-pdf.js
  } catch (err) {
    console.error(
      "SendGrid error:", 
      err.response?.body?.errors || err.message
    );
    return {
      statusCode: 500,
      headers:    CORS_HEADERS,
      body:       JSON.stringify({
        error: err.response?.body?.errors || err.message
      })
    };
  }

  // 3) Now handle the real POST
  if (event.headers["x-api-key"] !== process.env.FUNC_API_KEY) {
    return {
      statusCode: 401,
      headers:    CORS_HEADERS,
      body:       "Unauthorized"
    };
  }

  try {
    const { customer, pdfDataUri } = JSON.parse(event.body);
    const base64 = pdfDataUri.split(",")[1];

    const msg = {
      to:           "your.team@muriphys.com",
      from:         "no-reply@muriphys.com",
      subject:      `New PDF from ${customer.name || "Unknown"}`,
      text:         `PDF generated by ${customer.name} <${customer.email}>.`,
      attachments: [{
        content:     base64,
        filename:    "Muriphys_Project_Summary.pdf",
        type:        "application/pdf",
        disposition: "attachment"
      }]
    };

    await sgMail.send(msg);
    return {
      statusCode: 200,
      headers:    CORS_HEADERS,
      body:       "Email sent"
    };

  } catch (err) {
    console.error("SendGrid error:", err);
    return {
      statusCode: 500,
      headers:    CORS_HEADERS,
      body:       "Failed to send email"
    };
  }
};
